### ISSUE TITLE
CSV-Import funktioniert leider nicht und "Neue Stunde" anlegen endet mit Serverfehler

### ISSUE THREAD

**Issue by c3schulto** [polarwinkel/GradeMan#2]
Hallo Dirk,
ich habe den guten alten Grademan jetzt erst einmal der Version 2 vorgezogen wie du vorgeschlagen hast, aber leider funktioniert der Import der CSV-Dateien nicht wie gewohnt. Ist das mein Problem oder liegt es irgendwie an der Umstellung auf Python3? Danke und Gruß, Christian

Das gibt die Konsole aus:

127.0.0.1 - - [04/Sep/2023 10:55:32] "GET /kurs/0 HTTP/1.1" 200 3350
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bottle.py", line 869, in _handle
    return route.call(**args)
  File "/usr/lib/python3/dist-packages/bottle.py", line 1749, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/grademan/GmServer.py", line 154, in kurschange
    for row in schliste:
_csv.Error: iterator should return strings, not bytes (the file should be opened in text mode)

**Comment by c3schulto** [comment]
Hallo, noch ein Nachtrag:
ich bekomme auch wenn ich eine neue Stunde erstellen will eine Fehlermeldung:

Error: 500 Internal Server Error
Sorry, the requested URL 'http://localhost:8084/stunde/change' caused an error:
Internal Server Error

Nach erneutem laden der Seite wird die Stunde aber letztlich angelegt.

Und die Konsole zeigt das hier:
127.0.0.1 - - [04/Sep/2023 20:11:23] "GET /stunde/new/14/1 HTTP/1.1" 200 1910
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bottle.py", line 869, in _handle
    return route.call(**args)
  File "/usr/lib/python3/dist-packages/bottle.py", line 1749, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/grademan/GmServer.py", line 451, in stundenchange
    self.data['teilnahmen'].sort(key=attrgetter('schueler.vorname'), cmp=locale.strcoll)
TypeError: 'cmp' is an invalid keyword argument for sort()
127.0.0.1 - - [04/Sep/2023 20:11:33] "POST /stunde/change HTTP/1.1" 500 754

Ist die Ursache für beide Fehlermeldungen möglicherweise die gleiche?
Mein System: Ubuntu 22.04, Python3.10.6-1

**Comment by polarwinkel** [comment]
Moin c3schulto,
danke für die Fehlermeldung.

> _csv.Error: iterator should return strings, not bytes (the file should be opened in text mode)

Das deutet darauf hin, dass die Datei in einem falschen Format vorliegt.
Hast du sie genau wie in der Hilfe `/help#csvfile` gespeichert, auch in `utf-8`-codierung? (Einstellungen werden z.B. in LibreOffice Calc beim Export abgefragt)? Noch mal im Texteditor geöffnet und geschaut ob es passt?

Der zweite Fehler sieht im moment harmloser aus, GradeMan scheint noch nicht vorhandene Teilnahmen sortieren zu wollen, was freilich scheitert.
Ich vermute im Moment mal dass das auch daran liegt, dass der Kurs noch leer ist (keine Schüler), kann das sein?

**Comment by c3schulto** [comment]
Moin Dirk,
danke für den Hinweis. Das Problem habe ich in den Letzten 10 Jahren schon mal gehabt und ich achte eigentlich darauf dass die csv korrekt erstellt ist. ;-) Ich habe es mir einfach gemacht und die identische csv auf einem anderen PC mit Grademan classic 3.2 und python2  zu importieren versucht, ganz ohne Probleme. ebenso hat eine "alte" csv vom letzten Schuljahr bei grademan3.3.3 un dpython3 NICHT funktioniert.

Ich hatte die .deb installiert, habe jetzt wie früher gewohnt noch einmal die aktuelle .zip-Datei heruntergeladen und entpackt und gestartet. Dort kann ich ebenso einzelne SuS erstellen, kann sie aber NICHT einzeln einem Kurs hinzugfügen, was bei der aktuellen .deb-Version jedenfalls trotz Serverfehlermeldung dann doch geht. Recht merkwürdig, oder? Ich aktualisiere jetzt nochmal mein system inkl. python.

Gruß, Christian

**Comment by polarwinkel** [comment]
Moin Christian,
ok, danke fürs testen, ich schaue es mir mal die Tage an, vermutlich treten die Fehler dann auch auf debian auf.
(Mit der snap-Pflicht habe ich Ubuntu den Rücken gekehrt)

Da ich GradeMan "Classic" selbst nicht mehr nutze merke ich sowas nicht. Da es aber noch einige Nutzer gibt die sich gemeldet hatten habe ich es noch zu python3 portiert, dann aber eben offenbar nicht mehr ausgiebig genug getestet.

**Comment by c3schulto** [comment]
Hallo, vielen Dank! Was willst du denn zuerst machen, die Änderungen an Grademan2 oder Grademan classic reparieren? Ich müsstre mich nun doch möglichst bald entscheiden, auf welches Pferd ich setze, ob ich in Bezug auf das begonnene Schljahr jetzt eine db.pickle oder eine  grademan.sqlite3 "füttere" ;-) Gruß, Christian

**Comment by polarwinkel** [comment]
Ich habe gerade mal reingeschaut, die verwendete bottle-bibliothek/framework hatte Änderungen.
Schau mal ob es jetzt bei dir geht (bedarfsweise einfach die die GmServer.py durch die neueste upstream ersetzen)

**Comment by polarwinkel** [comment]
Ach, und wenn du testest: Kannst du mal kurz schauen ob die alphabetische Sortierung noch klappt? Das war das Problem mit dem `cmp` was in python3 nicht mehr existiert. Ich hatte gerade nur zwei testnamen verwendet.

**Comment by c3schulto** [comment]
Hallo Dirk,
vielen Dank für deine Mühe. Ja, es klappt grundsätzlich. Auch die alphabetische Sortierung stimmt. Bisher bemerkte Einschränkungen:
1:
Obwohl der CSV-Import  funktioniert, meckert er zunächst mit einem Serverfehler. Erst nachdem man die Kurs-Seite neu lädt, sieht man dass es doch geklappt hat.  (Siehe unten: Zwei händisch eingefügte SuS, dann der Import mit Fehlermeldung.
2:
Bei Kursnamen und Schülernamen werden z.B. Umlaute korrekt angezeigt, in den Textfeldern für Stundenverlauf, Notizen usw. formatiert er diese ganz kryptisch um.




127.0.0.1 - - [13/Sep/2023 20:22:50] "GET /kurs/0/add/ HTTP/1.1" 200 1180
127.0.0.1 - - [13/Sep/2023 20:22:53] "GET /kurs/0/add/1 HTTP/1.1" 200 1132
127.0.0.1 - - [13/Sep/2023 20:22:57] "GET /kurs/0/add/0 HTTP/1.1" 200 1084
127.0.0.1 - - [13/Sep/2023 20:23:04] "GET /kurs/0 HTTP/1.1" 200 3444
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bottle.py", line 869, in _handle
    return route.call(**args)
  File "/usr/lib/python3/dist-packages/bottle.py", line 1749, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/grademan/GmServer.py", line 175, in kurschange
    if picfile.file.getbuffer().nbytes > 0:
AttributeError: 'NoneType' object has no attribute 'file'
127.0.0.1 - - [13/Sep/2023 20:23:18] "POST /kurs/change HTTP/1.1" 500 752
127.0.0.1 - - [13/Sep/2023 20:23:57] "GET /kursuebersicht/0 HTTP/1.1" 200 6166

**Comment by c3schulto** [comment]
Hallo Dirk, ich habe gerade eben bemerkt dass ich das Curriculum sowie die Leistungsübersicht auch nicht anzeigen kann. Da hilft leider auch nicht wenn ich die Seite neu zu laden versuche, wie es bei der Stundenansicht geht. Ich habe gerade keine Zeit, die Ausgabe der Konsole zu posten, das hole ich nacher mal nach. Gruß, Christian
